name: cazdata_frontend
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    # The following adds the Cupertino Icons font to your application.
    # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  provider: ^4.3.2+1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_database: ^4.0.0
  google_sign_in: ^4.1.1
  location: ^3.0.0
  google_maps_flutter: ^0.5.28+1
  rxdart: 0.23.1
  redux: ^4.0.0
  flutter_redux: ^0.6.0
  redux_thunk: ^0.3.0
  auto_size_text: ^2.1.0
  custom_radio_grouped_button: any
  flutter_dotenv: ^2.1.0
  flutter_speed_dial: ^1.2.5
  flutter_polyline_points: ^0.2.2
  latlong: ^0.6.1
  cloud_firestore: ^0.14.0+2
  big_tip: ^1.1.1
  google_fonts: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 800
  assets:
    - assets/
    - .env

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
